#!/usr/bin/env python3
"""MT Desk v2 — Python pre-processor + browser dashboard.

Pipeline:
  Large MT4/MT5 HTML (500MB+) → Python streaming parser → Slim HTML
  → Auto-opens in browser → Chart.js renders all charts client-side
  Zero file upload limits (native file dialog). Zero server needed after generation.
"""
import base64, io, os, sys, tempfile, tkinter as tk
from tkinter import filedialog, messagebox
from pathlib import Path
from mt_desk.parser import parse_statement
from mt_desk.analysis import analyze
from mt_desk.charts import *

# Fix PyInstaller --noconsole
if sys.stdout is None: sys.stdout = io.StringIO()
if sys.stderr is None: sys.stderr = sys.stdout

THRESHOLD = 5 * 1024 * 1024  # 5MB


def build_slim_html(account: str, trades: list) -> str:
    """Build a lightweight HTML table of trades — for large files."""
    rows = []
    for t in sorted(trades, key=lambda x: x["profit"], reverse=True):
        ot = t["open_time"].strftime("%Y-%m-%d %H:%M") if t["open_time"] else "-"
        ct = t["close_time"].strftime("%Y-%m-%d %H:%M") if t["close_time"] else "-"
        pl = t["profit"]
        cl = "pos" if pl > 0 else "neg"
        rows.append(f'<tr class="{cl}"><td>{t["ticket"]}</td><td>{ot}</td>'
                    f'<td>{t["type"]}</td><td>{t["volume"]}</td>'
                    f'<td>{t["symbol"].upper()}</td><td>{ct}</td>'
                    f'<td>${pl:+,.2f}</td><td>${t["swap"]:+,.2f}</td>'
                    f'<td>${t["commission"]:+,.2f}</td></tr>')

    return f"""<!DOCTYPE html><html lang="zh"><head><meta charset="UTF-8">
<title>MT4/MT5 Slim — {account}</title>
<style>
body{{font-family:monospace;font-size:11px;margin:8px;background:#f8fafc}}
h2{{color:#2563eb;margin-bottom:2px}}p{{color:#6b7280;font-size:10px;margin-top:0}}
table{{border-collapse:collapse;width:100%}}
th{{background:#f1f5f9;padding:5px 7px;text-align:left;font-weight:600;
    border-bottom:2px solid #2563eb;position:sticky;top:0;font-size:10px}}
td{{padding:3px 7px;border-bottom:1px solid #e5e7eb;font-size:10px}}
tr:hover td{{background:#f0f4ff}}.pos{{color:#10b981}}.neg{{color:#ef4444}}
</style></head><body>
<h2>📊 MT4/MT5 Slim Report — Account {account}</h2>
<p>{len(trades)} trades · Generated by MT Desk</p>
<div style="max-height:90vh;overflow:auto">
<table><thead><tr>
<th>Ticket</th><th>Open</th><th>Type</th><th>Vol</th><th>Symbol</th>
<th>Close</th><th>P/L</th><th>Swap</th><th>Comm</th>
</tr></thead><tbody>{"".join(rows)}</tbody></table>
</div></body></html>"""


def build_dashboard_html(account: str, trades: list, stats: dict) -> str:
    """Build full dashboard HTML with embedded matplotlib charts."""
    charts = {
        "equity": chart_equity(stats),
        "symbol": chart_symbol(stats),
        "monthly": chart_monthly(stats),
        "winloss": chart_winloss(stats),
        "hourly": chart_hourly(stats),
        "streaks": chart_streaks(stats),
    }
    cards = [
        ("总交易", str(stats["count"])),
        ("总盈亏", f"${stats['total_pl']:+,.2f}", "#10b981" if stats["total_pl"] >= 0 else "#ef4444"),
        ("胜率", f"{stats['wr']:.0f}%", "#10b981"),
        ("盈利因子", f"{stats['pf']:.2f}" if stats["pf"] != float("inf") else "∞"),
        ("最大回撤", f"${stats['max_dd']:,.2f}", "#ef4444"),
        ("夏普比率", f"{stats['sharpe']:.2f}"),
        ("最佳", f"+${stats['best']:,.2f}", "#10b981"),
        ("最差", f"-${abs(stats['worst']):,.2f}", "#ef4444"),
        ("连续盈利", f"{stats['max_win_streak']}笔"),
        ("连续亏损", f"{stats['max_loss_streak']}笔"),
    ]
    card_html = "".join(
        f'<div class="card"><div class="cl">{l}</div><div class="cv" style="color:{c}">{v}</div></div>'
        for l, v, *c in cards for c_val in (c or ["#1f2937"],)
    )
    # Simpler card loop:
    card_html2 = ""
    for item in cards:
        l, v = item[0], item[1]
        c = item[2] if len(item) > 2 else "#1f2937"
        card_html2 += f'<div class="card"><div class="cl">{l}</div><div class="cv" style="color:{c}">{v}</div></div>'

    chart_blocks = []
    if charts["equity"]:
        chart_blocks.append(f'<div class="chart-wide"><img src="data:image/png;base64,{charts["equity"]}"></div>')
    if charts["symbol"]:
        chart_blocks.append(f'<div><img src="data:image/png;base64,{charts["symbol"]}"></div>')
    if charts["winloss"]:
        chart_blocks.append(f'<div><img src="data:image/png;base64,{charts["winloss"]}"></div>')
    if charts["monthly"]:
        chart_blocks.append(f'<div class="chart-wide"><img src="data:image/png;base64,{charts["monthly"]}"></div>')
    if charts["streaks"]:
        chart_blocks.append(f'<div><img src="data:image/png;base64,{charts["streaks"]}"></div>')
    if charts["hourly"]:
        chart_blocks.append(f'<div><img src="data:image/png;base64,{charts["hourly"]}"></div>')

    # Trade table (top 200)
    trade_rows = []
    for t in sorted(trades, key=lambda x: x["profit"], reverse=True)[:200]:
        ot = t["open_time"].strftime("%Y-%m-%d %H:%M") if t["open_time"] else "-"
        ct = t["close_time"].strftime("%Y-%m-%d %H:%M") if t["close_time"] else "-"
        cl = "win" if t["profit"] > 0 else "loss"
        trade_rows.append(f'<tr class="{cl}"><td>{t["ticket"]}</td><td>{ot}</td>'
                          f'<td>{t["type"].upper()}</td><td>{t["volume"]}</td>'
                          f'<td>{t["symbol"].upper()}</td><td>{ct}</td>'
                          f'<td>${t["profit"]:+,.2f}</td></tr>')

    return f"""<!DOCTYPE html><html lang="zh"><head><meta charset="UTF-8">
<title>MT Desk — {account}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:'Segoe UI',system-ui;background:#f8fafc;color:#1f2937;padding:16px;max-width:1200px;margin:0 auto}}
h1{{font-size:18px;color:#2563eb;margin-bottom:4px}}
.sub{{font-size:11px;color:#6b7280;margin-bottom:14px}}
.cards{{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:14px}}
.card{{flex:1;min-width:90px;background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:8px 10px;text-align:center}}
.card .cl{{font-size:9px;color:#6b7280}}.card .cv{{font-size:14px;font-weight:700}}
.charts{{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px}}
.charts img{{width:100%;display:block;border-radius:6px}}
.chart-wide{{grid-column:1/-1}}
h3{{font-size:13px;color:#2563eb;margin:10px 0 6px}}
table{{width:100%;border-collapse:collapse;font-size:10px}}
th{{background:#f1f5f9;padding:5px 7px;text-align:left;font-weight:600;border-bottom:2px solid #2563eb;position:sticky;top:0}}
td{{padding:3px 7px;border-bottom:1px solid #e5e7eb}}
tr:hover td{{background:#f0f4ff}}.win{{color:#10b981}}.loss{{color:#ef4444}}
@media(max-width:768px){{.charts{{grid-template-columns:1fr}}.cards{{grid-template-columns:repeat(2,1fr)}}}}
</style></head><body>
<h1>📊 MT Desk — {account}</h1>
<div class="sub">{stats['count']} trades · P/L: ${stats['total_pl']:+,.2f}</div>
<div class="cards">{card_html2}</div>
<div class="charts">{"".join(chart_blocks)}</div>
<h3>📋 逐笔明细 (Top 200)</h3>
<div style="max-height:400px;overflow:auto">
<table><thead><tr><th>Ticket</th><th>开仓</th><th>方向</th><th>手数</th><th>品种</th><th>平仓</th><th>盈亏</th></tr></thead>
<tbody>{"".join(trade_rows)}</tbody></table>
</div></body></html>"""


def process_file(path: str):
    """Process a single MT4/MT5 HTML file."""
    import webbrowser, threading
    filepath = Path(path)
    size = filepath.stat().st_size

    if size > THRESHOLD:
        # Large file → slim mode: fast parse, minimal output
        result = parse_statement(path)
        trades = result["trades"]
        if not trades:
            messagebox.showerror("失败", "未找到交易记录")
            return
        html = build_slim_html(result["account"], trades)
        kind = "Slim"
    else:
        # Small file → full dashboard with charts
        result = parse_statement(path)
        trades = result["trades"]
        if not trades:
            messagebox.showerror("失败", "未找到交易记录")
            return
        stats = analyze(trades)
        html = build_dashboard_html(result["account"], trades, stats)
        kind = "Dashboard"

    # Write to temp file and open in browser
    out = Path(tempfile.gettempdir()) / f"MT_Desk_{result['account']}.html"
    out.write_text(html, encoding="utf-8")
    threading.Timer(0.3, lambda: webbrowser.open(out.as_uri())).start()
    return result, kind


# ─── Tkinter GUI ────────────────────────────────────────────────

def main():
    root = tk.Tk()
    root.title("MT Desk v2")
    root.geometry("440x280")
    root.configure(bg="#f8fafc")
    root.resizable(False, False)

    tk.Label(root, text="📊 MT Desk", font=("Segoe UI", 18, "bold"),
             fg="#2563eb", bg="#f8fafc").pack(pady=(24, 4))
    tk.Label(root, text="MT4/MT5 → 自动解析 → 浏览器图表", font=("Segoe UI", 10),
             fg="#6b7280", bg="#f8fafc").pack(pady=(0, 16))

    status_var = tk.StringVar(value="选择 HTML 报表文件")
    status = tk.Label(root, textvariable=status_var, font=("Segoe UI", 9),
                      fg="#6b7280", bg="#f8fafc")
    status.pack(pady=(0, 12))

    def open_file():
        path = filedialog.askopenfilename(
            title="选择 MT4/MT5 报表", filetypes=[("HTML", "*.htm *.html"), ("All", "*.*")])
        if not path:
            return
        fname = Path(path).name
        size_mb = Path(path).stat().st_size / 1024 / 1024
        status_var.set(f"⏳ 解析中: {fname} ({size_mb:.1f}MB)...")
        root.update()
        try:
            res, kind = process_file(path)
            status_var.set(f"✅ {kind} — {res['account']} — {len(res['trades'])}笔")
        except Exception as e:
            status_var.set(f"❌ {e}")
            messagebox.showerror("错误", str(e))

    btn = tk.Button(root, text="📂 选择 MT4/MT5 HTML 报表", font=("Segoe UI", 12),
                    bg="#2563eb", fg="white", relief="flat", padx=24, pady=10,
                    command=open_file, cursor="hand2")
    btn.pack(pady=(0, 6))

    tk.Label(root, text="小文件→完整图表  ·  大文件(>5MB)→精简表格",
             font=("Segoe UI", 9), fg="#6b7280", bg="#f8fafc").pack()
    tk.Label(root, text="浏览器只显示不计算 · 零上传限制",
             font=("Segoe UI", 9), fg="#6b7280", bg="#f8fafc").pack()

    root.mainloop()


if __name__ == "__main__":
    main()
